### ISSUE TITLE
How do you search for modules to download?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/community#190]
From the plugin manager I can see a bunch of things, but to find out what they do it seems I need to click on the manual and read that. Is there an easier way to, for example, search for filters?

**Comment by AndrewBelt** [comment]
> I need to click on the manual and read that

That's how I'd recommend doing it. You can also click on the homepage or developer name if a hyperlink is available. Searching only filters by name of plugin and developer.

**Comment by squinkylabs** [comment]
> That's how I'd recommend doing it.

That's not going to scale too well, but I guess cross that bridge when you come to it. It sure would be nice if the plugin manager showed a one line description of the module!

**Comment by AndrewBelt** [comment]
Note that a plugin contains multiple modules.

It is not the Plugin Manager's job to help you shop for modules, that's what the homepage will be for in the next version of the website. It will have boxes of featured products like [apple.com](https://www.apple.com/)'s homepage so you can ogle at the panel graphics instead of rely on reading text. The page will prefer polished plugins, so as you might expect, there will be a higher proportion of commercial modules compared to noncommercial ones on the homepage. I can't be held responsible for curating low-quality plugins since it is too time consuming.

**Comment by squinkylabs** [comment]
That sounds like a perfect idea. thanks!

(and yes, I did notice that plugins have multiple modules - it's one of the (many) things that makes it look like developing plugins for VCVRack is easier (more fun) than other platforms. I remember it took me a day or something the get my VST plugins to do that.)

**Comment by squinkylabs** [comment]
coincidence: I was using the free "Brackets" editor to browse the VCRack code base. Brackets plugin manager does in fact display a short description of each plugin.

**Comment by AndrewBelt** [comment]
Merging discussion with #243
