### ISSUE TITLE
Add Author Field

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/community#3]
The spec has no field for `author`. I think people should get credit for their work.

**Comment by AndrewBelt** [comment]
Hmm, I decided against this because authors can change hands, contributions can come from many people, and there can be companies involved. For example, if you look at most NPM packages, the "author" key typically holds the founder's name, but sometimes the founder is only responsible for 30% of the code.

I think the author is best portrayed by the "homepage" and "source" keys. If someone wants to truly find out who wrote the software, they should get the full details, not an out of date summary.

I'd consider it though if others chime in, since it's kind of a "free" key.

**Comment by AndrewBelt** [comment]
Decided on no, since the purpose of these JSON manifests serve one reason: to be displayed on the future vcvrack.com/manager (or whatever) website, and there's no room for an author field, just links to where we can find out information about the author. Just makes extra useless work for creating manifests.

**Comment by AndrewBelt** [comment]
Just added some room to the plugin manager webpage, so we can have an author field now, woo!
