### ISSUE TITLE
Is there an ETA when the plugins will get rebuilt?

### ISSUE THREAD

**Issue by almostEric** [VCVRack/community#405]
Looks like there is quite a stack of plugins that are waiting to be released. Mine was released with an old code base, so I submitted an issue to update to 0.6.1 a few days ago and still no word other than a Plug In tag being added

**Comment by phdsg** [comment]
previous update commit by @cschol was reverted.
i think that was before the review/update workflow was posted and we have to change a different field in the manifest to trigger a rebuild.

**Comment by almostEric** [comment]
I thought that was the whole point - we no longer did pull requests on our manifest, but submitted issues with what changed (urls, ettc.) and versionNumber : 0.6.1, I would think would trigger the rebuild. seeing that there 14 open tickets for people waiting to get their plugins updated, something doesn't seem quite right

**Comment by AndrewBelt** [comment]
April 4 at the latest.
Currently I think there are no repos out of sync with their builds. https://github.com/VCVRack/community/pull/403 would make two of them.

**Comment by almostEric** [comment]
Hi Andrew,

 

I updated the version of Frozen Wasteland (through Issue #387) hoping a new build would be done because 0.6.0 didn’t use my latest code. From reading the issues, there are a lot more than two out of sync. Appreciate all your work – are you the only one doing library builds? I thought you had some help now?

 

Eric

**Comment by AndrewBelt** [comment]
The submodule commit hash in the community repository for FrozenWasteland is 1b3f14483d1a005d6693c4ccff74b07029f1c3ff. This needs to be updated, but a Review team member has not updated it yet.

**Comment by mdemanett** [comment]
I reviewed Eric's code and filed a PR to update the module pointer (the manifest is already done).

Andrew, let me know if I've misunderstood what needed to be done here.

**Comment by AndrewBelt** [comment]
Build Team progress https://github.com/VCVRack/community/issues/353#issuecomment-377828685

**Comment by JerrySievert** [comment]
any thoughts on going back to a more developer in control release process?  this isn't working, and I already have a couple of modules that I haven't wanted to update to 0.6, and am not feeling good about updating or adding to the rest of my modules because it has been so opaque,

I'd love to have some sort of idea of what's going on again, please.

**Comment by AndrewBelt** [comment]
@JerrySievert Can you be patient? I'm with my family for Easter, and you're expecting me to release builds for your plugin, a task that I don't get paid a penny for?

**Comment by phdsg** [comment]
@JerrySievert also, what exactly is not working? you want your current modules pulled from the plugin manager? or an update? please file an issue for the plugin as described here: https://github.com/VCVRack/community#for-plugin-developers

**Comment by JerrySievert** [comment]
@phdsg and @AndrewBelt I think you both have just underscored some of the issues - a request to remove the opaqueness and go back to the developers being in control is suddenly a problem.  I don't ask money for the plugins I develop (or hell, from the few millions users for the open source projects I maintain myself), and am not asking you to spend your own time maintaining my work, I'd be very happy to compile my own plugins, because at least it was my own fault if something didn't get done.

I brought it up after getting a request myself to help friends build over the holiday, not for a lecture for asking for some clarity.

**Comment by phdsg** [comment]
@JerrySievert not sure, what you mean by "opaqueness"...
what exactly is unclear about the process?

**Comment by JerrySievert** [comment]
@phdsg well, all of it? current status, how to get releases out without issues, how any sort of feedback process works without issues, build systems in general, that all of the feedback is missing from the process is a problem, and when there is feedback there seems to be friction.

that we're having this conversation is just silly.

**Comment by AndrewBelt** [comment]
@JerrySievert Do you not remember the "red dot" issues with Rack 0.5? 75% of those issues were because plugin developers were not using `make dist`, using different ways to create ZIP packages, forgetting to synchronize the VERSION in their Makefile, and using incorrect plugin slugs. Basically, I learned that a developer-controlled manifest database and build system was completely unviable (I should have seen that from the start but didn't consider it). So, we've switched to a centralized team of a smaller number of well-trained volunteers  (4-5 people) following a tight procedure instead of all 100 plugin developers using their own creative way of packaging their files in broken ways. The Rack 0.6 release has gone well with very few people having issues syncing their plugins.

We also had a huge discussion a couple months ago about the dangers and solutions of accepting random strangers into Rack's distribution system to push arbitrary binaries without review. The solution was to review source code for malicious code to increase the trust of Plugin Manager packages. If someone I've never met gives me a binary, I wouldn't run it myself, so I certainly shouldn't distribute it for tens of thousands of people to use.

**Comment by JerrySievert** [comment]
> 75% of those issues were because plugin developers were not using make dist, using different ways to create ZIP packages, forgetting to synchronize the VERSION in their Makefile, and using incorrect plugin slugs. I learned that a developer-controlled manifest database and build system was completely unviable (I should have seen that from the start but didn't consider it).

large developer controlled ecosystems (node, postgres, python, perl, etc) would likely disagree with that assertion, but those ecosystems have more stable targets, which might be part of the issue - you have to understand that we're compiling against a fast moving target, that hasn't seemed stable, and when anyone has brought it up, it has been "their" problem, because they tried to bring up issues.

>  Still, about 75% of developers get something wrong about their proposed manifest file or source tree, but that's totally fine now. When the Library and Review team update the manifests with a PR, they fix all these problems with much greater efficiency and reliability than most individual developers would.

that would be the same manifest system that had horribly broken tests and was ignored?

> If someone I've never met gives me a binary, I wouldn't run it myself, so I certainly shouldn't distribute it for tens of thousands of people to use.

must really suck to compile all of those packages from scratch without a c compiler :)

some of what you're saying I would agree with, but you're pushing a heckofa lot of blame onto the developers that are doing quite a bit of work on this platform - there are quite a few very intelligent people with a ton of experience trying to help, but it feels like a hostile environment.  I stepped up and asked the questions that were being asked of me after I convinced several people to change environments they were writing software for, and feel like I've been attacked for it.

**Comment by AndrewBelt** [comment]
I've answered your question, closing discussion.

**Comment by JerrySievert** [comment]
my question wasn't why this issue was opened.  par for the course?

**Comment by phdsg** [comment]
@JerrySievert i still don't get it. in your first post here you said "this isn't working" and something about not feeling good updating your modules...
so what exactly is wrong with the current version of your modules on the plugin manager and what can we do to change that? update them? remove them?

**Comment by JerrySievert** [comment]
@phdsg I asked for transparency, and instead got developer blame - I'm just looking for some answers and not getting them.

**Comment by phdsg** [comment]
the initial question was answered already before you chimed in: https://github.com/VCVRack/community/issues/405#issuecomment-377676393

**Comment by JerrySievert** [comment]
<img width="398" alt="screen shot 2018-04-02 at 2 09 12 pm" src="https://user-images.githubusercontent.com/471270/38216390-7a24b494-367f-11e8-8b2e-5acfb63acb10.png">

hm, somehow I thought there would be some sort of discussion here.

**Comment by AndrewBelt** [comment]
@JerrySievert If you have a withstanding question, please open your own issue. This issue discussion has been concluded when the ETA was stated.
