### ISSUE TITLE
Version Is Confusing

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/community#5]
You might not like this one, Andrew. :[

We should split `version` and `rack_version` into different fields. It is very [confusing](https://github.com/VCVRack/community/pull/2#issuecomment-348183418) and non-standard to have two different meanings jammed into a single string. It certainly isn't the intention of semantic versioning to do this, so calling it semantic might be another source of this confusion.

I realize that changing it _again_ is going to make it even more confusing in the short term, but I think it's the right thing to do in the long wrong.

**Comment by AndrewBelt** [comment]
Rack uses standard semantic versioning (well, after v1.0. pre-v1.0 is a modification).

Plugins don't use standard versioning, they use the standard defined in #266. Here's another way of stating it, pre-Rack v1.0:

Version: `vX.Y.Z`

Split these into
- Rack version: `vX.Y`
- Plugin version: `.Z`

**Comment by Miserlou** [comment]
So, can developers use semantic versioning? Ex, `vRX.RY.RZ.PX.PY.PZ`?

**Comment by AndrewBelt** [comment]
You can use whatever string you want after "vX." (after Rack v1.0).

I would discourage your proposed usage because it decouples the release cycle of Rack from the plugins. I believe that modules should not add new features after release, only bug fixes (i.e. get it right on the first release), but if they do, they should wait until a major version release of Rack.
