### ISSUE TITLE
[Discussion] Build Box Architecture and Deployment

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/community#6]
We can use this thread to discuss how we want to built an automated test/build/delivery system for merged.

OSX and Linux builds shouldn't be any problem, but Windows builds might. I _think_ we can cross compile from Linux to Windows if we install the correct headers and stuff.

I suggest that we come up with a Docker image which can cross compile for all three platforms. That way, we can share that image with anybody who wants to build for all three without using the build box.

Related, we may also want to add `build_author` and `signature` fields to the manifest as well.

**Comment by TyIsI** [comment]
Looking at other projects, this could even be done automatically through a CI implementation like Travis or perhaps even CircleCI.

**Comment by AndrewBelt** [comment]
Anyone is free to volunteer...

**Comment by Miserlou** [comment]
Yes, with a Docker-based infrastructure this could be done easily on CI, which is what I was considering. It's really just the issue of building Windows-compatible modules from a Linux container is the only thing from stopping this. See #509 above.

**Comment by AndrewBelt** [comment]
And yes, I'll add build_author if it's a requirement for your time, although there's not enough space on the Plugin Manager webpage to list it. Signature is probably unnecessary since you could just host it from some official domain or GitHub project, which would be enough to validate your identity. (And we let random people build their own plugins anyway, so there are worse problems if security is your concern.)

**Comment by TyIsI** [comment]
I'm going to try and spend some time on this in the nearer future

**Comment by AndrewBelt** [comment]
@TyIsI You should probably wait until after I design the "Build Team workflow" #248

**Comment by AndrewBelt** [comment]
Mergin with #353
