### ISSUE TITLE
Dintree-Virtual

### ISSUE THREAD

**Issue by hires** [VCVRack/community#656]
First VCV module:
- source code: https://github.com/hires/Dintree-Virtual
- version: 1.0.0
- commit hash:  e26fd5d

Thanks!

**Comment by AndrewBelt** [comment]
1. Please remove the string "VCV" from the slug, since this may confuse users into thinking that this is a VCV product. "Dintree" would be a good slug.
2. Your license is contradictory/invalid, so this needs to be fixed. Since contradictory licenses can't stand up in law, the "license" property should be "proprietary". We're still happy to include proprietary plugins in the VCV Library though.

**Comment by hires** [comment]
Sorry about that. The new slug is "Dintree-Virtual". I edited the URL on the first post just in case. The license has been fixed to remove any proprietary wording.

new version: 1.0.1
new commit hash: 2241895

**Comment by cschol** [comment]
Invalid URL in `plugin.json`: https://github.com/hires/Dintree-Virtual/issues/1

**Comment by hires** [comment]
Fixed. 

ver: 1.0.3
hash: 3211ea2

**Comment by AndrewBelt** [comment]
Thanks for changing the slug. You're allowed to say "Dintree VCV Rack modules" or "for VCV Rack" etc, but we just don't want people using the "VCV" trademark in the *name* of their software (and the slug is sort of the technical name of a Rack plugin).

Are you sure GPLv3+ is what you want? It seemed like your original intention was to prevent this software from being used in hardware microcontrollers. You can still do that if you wish, but you can't use the GPLv3 because your "additional requirement" contradicts what the GPLv3 says people can do with the software. It's analogous to someone writing "You can play my song on any radio station. You can only play my song on east coast radio stations." Since those statements cannot coexist, a lawyer could easily argue that the license is invalid. What you could do instead if you wish is write a non-open-source (freeware-type) license that only grants permission to redistribute and compile but does not allow source code modifications. Just a possibility, you can choose whatever you wish.

And one last thing: Since we haven't released any builds yet, you can start at version 1.0.0.

**Comment by hires** [comment]
Thanks for your advice. I totally understand the licensing thing. For now I’m just going to go ahead and work on open stuff under GPL for the Dintree-Virtual series. I will consider another line under my Kilpatrick Audio brand later with perhaps a different license.

As for the version it doesn’t matter to me that it starts at 1.0.3... I bumped it each time I made a new request as indicated in the manual. Please just start with it there if that’s okay.

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with then next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by hires** [comment]
Added two more modules!

new version: 1.0.6
new hash: b1b3eba

Thanks!

**Comment by hires** [comment]
Added more modules.

hash: 4e2c357
version: 1.0.9

Thanks!

**Comment by cschol** [comment]
Invalid tags in `plugin.json`: https://github.com/hires/Dintree-Virtual/issues/2

**Comment by hires** [comment]
Sorry about that.

new hash: 5774fb2
new version: 1.0.10

BTW where is the code for the checker used for this? I would like to run it here before submitting.

**Comment by cschol** [comment]
Thanks for fixing.

You can look at the scripts I wrote and use for integration checks here:
https://github.com/cschol/vcv-library-tools

Note, that these are for my own personal workflow and not supported (yet) in any way.

**Comment by hires** [comment]
Several bug fixes.

new version: 1.0.11
hash: 46808b0

Thanks!

**Comment by hires** [comment]
A few tweaks plus two new modules!

new version: 1.0.13
hash: 36391f7

Thanks!

**Comment by hires** [comment]
Some cleanup and better dark panels.

new version: 1.0.14
hash: 4b08482

Thanks!

**Comment by hires** [comment]
Rack2 support!

new version: 2.0.15
hash: 704c65b

Thanks!

**Comment by kilpatrickaudio** [comment]
Fixed some font stuff and code cleanup.

new version: 2.0.17
hash: d9f9d9b 

Thanks!
