### ISSUE TITLE
Crashes on Windows platform

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/community#669]
It's probably just superstition on my part, but when I was going though that crashing stuff last week and the week before the only thing I could think of is that "something" is different between local builds and tooling server builds for windows.

If course the linkage is different. I was unable (in the sort amount of time I tried) to generate a static link locally.

Seems like it would "be nice" if it were possible to make the two builds more similar? Anyway, the worry is that someone else will run into this mystery issues and their plugins will start crashing (like one of the people reporting constant win crashes.

fwiw my issues were 100% repro, so doesn't sound quite the same.

**Comment by cschol** [comment]
This is potentially an issue with cross-compilation. For `v2` I am updating the cross-compilation toolchain for Windows to the latest available compilers. Also, I think this issue is discussed in the [rack-plugin-toolchain](https://github.com/VCVRack/rack-plugin-toolchain/issues/5) repo. I am closing this issue.
