### ISSUE TITLE
WaporwareWTF

### ISSUE THREAD

**Issue by wapordev** [VCVRack/community#692]
Source code: https://github.com/lukester535/WaporwareWTF
Version: 1.0.0
Commit hash: 64e053253fb668bcd840675a003201b0c82d78c8

**Comment by cschol** [comment]
Your plugin has been integrated and will be available for all supported platforms with the next Plugin Manager update. Please let us know in **this** issue when a new version is available. We will reopen it. Thank you for providing your plugin to the Rack community.

**Comment by AndrewBelt** [comment]
I believe the WaporwareWTF module in this plugin violates https://vcvrack.com/manual/PluginLicensing#VCV-Plugin-Ethics-Guidelines for https://www.modulargrid.net/e/dove-audio-wtf-oscillator- due to "model name" and "layout of components". These guidelines are required for distributing your plugin on the VCV Library. I will reopen if these issues are fixed, or you present written permission from Dove Audio.
