### ISSUE TITLE
[Discussion] Travis

### ISSUE THREAD

**Issue by Miserlou** [VCVRack/community#7]
If we set up a little script and a `.travis.yml`, Travis could automatically check stupid stuff like JSON formatting and required fields all being in place.

**Comment by AndrewBelt** [comment]
Go for it! I have no idea how to use Travis.

**Comment by jeremywen** [comment]
FYI I have been periodically running `jq '.' plugins/*` to make sure they are valid json.

**Comment by jeremywen** [comment]
Not sure we need to overcomplicate this.

**Comment by AndrewBelt** [comment]
Yeah IMO I don't like automated code quality stuff, especially for this project because I can glance at it in 0.2s and tell if it's valid JSON, so I wouldn't use it, but if @miserou wants it then it's fine.

**Comment by jeremywen** [comment]
We use travisci and circleci at my real job.  They are fine but they are also very large projects with thousands of tests so it makes more sense.

**Comment by jeremywen** [comment]
One of our projects can take about 2 hours to run tests LOL

**Comment by AndrewBelt** [comment]
Reopening because it would be nice to

- check valid JSON
- check valid SHA256
- upload to VirusTotal and assert less than 3 or so engines return suspicious for each ZIP

 @Miserlou?

**Comment by jeremywen** [comment]
I can do it if you don't want to or don't have time @Miserlou

**Comment by AndrewBelt** [comment]
VirusTotal has a [public API](https://www.virustotal.com/en/documentation/public-api/v2/) and I believe we satisfy the ToS. I don't think a synchronous API is available since the scans may take over a minute, but you can submit a file, get a ticket code, and poll on the code until all scans are complete.

**Comment by jeremywen** [comment]
This is now mostly implemented.  I am currently working on fixing my test on another branch.  I want to make sure I only scan zips if a download or sha256 value changes.  So this diff command is what I am fixing.  I am doing this because the zip scanning is time consuming and it is rate limited to 4 times in a minute.  So I only want to use virus total when we really need to.  So I will fix this test in the next day or so.

**Comment by AndrewBelt** [comment]
Additional assertions:

- ZIP must not contain a __MACOSX directory at root level. 
- ZIP must not be a [tarbomb](https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb). Yes, I know the first is a subset of this one, but it's better to have more feedback. 
- We might even want to assert that the single folder at root level is named as the slug of the plugin. I'm for this.

**Comment by jeremywen** [comment]
Also, saw that linux->lin fix.  I will add schema validation.  I will rework the tests to handle all these checks.  At first I was going to just do some simple checks and fail on any error.  I will rewrite it to be more like real tests for all these things.

**Comment by AndrewBelt** [comment]
I admit that I underestimated how sloppy people are.

**Comment by jeremywen** [comment]
done
