### ISSUE TITLE
NielsenPlugs-Panels

### ISSUE THREAD

**Issue by jpnielsen** [VCVRack/community#707]
Please add my plugin to the library.

Source Code URL:
https://github.com/jpnielsen/NielsenPlugs-Panels

Version:
2.0.2

Commit hash:
9301e72a0d172d1b9c4bb7f020ec1020bcac94c4

**Comment by jpnielsen** [comment]
Got this reply from VCV:

".. we generally don't accept panel-only plugins anymore unless they offer some kind of visual signal manipulation."

Closing.

**Comment by The-Great-Assyr** [comment]
How they justify then the blank panels that do nothing like Bogaudio, Mochba, Impromptu, AS, CF, Stellare, VCV itself, Quanta, Geodesic, wiqid, Submarine, JW and the many others that do not offer any visual manipulation and are present in the library?

**Comment by Petervos2018** [comment]
Not to bud in, but is says "anymore" which means "from now on" so the other modules were made before they stopped accepting panel-only modules. And that was/ is a shame because it was such a lovely module : 

![afbeelding](https://github.com/VCVRack/library/assets/46076474/7cf14d90-14d5-4b80-8ae3-0c6511eae175)

Here it is next to the new cytomic filter.
