### ISSUE TITLE
STS-Bundle

### ISSUE THREAD

**Issue by mlaban64** [VCVRack/community#791]
https://github.com/mlaban64/STS-Bundle

**Comment by AndrewBelt** [comment]
Before this is approved, I'd recommend removing the `STS-` prefix from module slugs and names since it's redundant.
I'd also recommend removing `-Bundle` from the plugin slug since all plugins are collections of modules.
The plugin name "STS" can be changed to "Sm@rTAZZ Studio Free" to be more specific.
The `dist/` folder should be removed from the git history, since binary data adds bloat to git repos. This folder should be added to `.gitignore`, which is included by our `helper.py` script.

**Comment by mlaban64** [comment]
Thanks Andrew, the feedback is appreciated!
 
I'll take care of this and post a new version shortly.
 
Regards,
Marinko
